GET https://backend-ex-tde8.onrender.com/api/persons
###
DELETE https://backend-ex-tde8.onrender.com/api/persons/2

###
POST https://backend-ex-tde8.onrender.com/api/persons
content-type: application/json

{
  "name": "Dan Abramov",
  "number": "12-234323"
}